name: text2cad
channels:
    - conda-forge
    - pytorch
    - defaults

dependencies:
    - python=3.9
    - numpy
    - pytorch::pytorch
    - pytorch::torchvision
    - pythonocc-core=7.7.2
    - pip
    - pip:
        - tqdm
        - prettytable
        - torchinfo==1.8.0
        - plyfile==0.9
        - trimesh==4.1.8
        - tensorboard
        - pyvista
        - rich==13.7.1
        - CythonGSL
        - loguru
        - torchdata==0.7.1
        - litdata
        - transformers
        - nltk
        - ipykernel
        - ipywidgets
        - rich
        - pillow
        - accelerate
        - python-dotenv
        - gradio
        - open3d